services:
  # Backend API service
  - type: web
    name: emotional-diary-api
    env: python
    region: frankfurt
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/emotional_diary
      - key: SECRET_KEY
        value: "your-secret-key-here"
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

  # Frontend service
  - type: static
    name: emotional-diary-frontend
    env: static
    region: frankfurt
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
      - key: REACT_APP_API_URL
        value: https://emotional-diary-api.onrender.com
